version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:8000 main:app
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
      - CELERY_BROKER_URL=${CELERY_BROKER_URL:redis://redis:6379/0}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND:redis://redis:6379/0}

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A celery_tasks worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL:redis://redis:6379/0}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND:redis://redis:6379/0}
