services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GIT_COMMIT_AUTHOR_NAME=${GIT_COMMIT_AUTHOR_NAME}
        - GIT_COMMIT_AUTHOR_EMAIL=${GIT_COMMIT_AUTHOR_EMAIL}
    image: github-app-aider
    pull_policy: never
    command: gunicorn --bind 0.0.0.0:8585 main:app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - FLASK_ENV=production
    volumes:
      - ./github-private-key.pem:/app/github-private-key.pem
    ports:
      - "8585:8585"
    depends_on:
      - redis

  celery_worker:
    image: github-app-aider
    pull_policy: never
    command: celery -A celery_tasks worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    volumes:
      - ./github-private-key.pem:/app/github-private-key.pem
    depends_on:
      - redis
      - web

  flower:
    image: github-app-aider
    pull_policy: never
    command: celery -A celery_tasks flower --port=5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./github-private-key.pem:/app/github-private-key.pem
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery_worker

  redis:
    image: redis:alpine
