services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GIT_COMMIT_AUTHOR_NAME=${GIT_COMMIT_AUTHOR_NAME}
        - GIT_COMMIT_AUTHOR_EMAIL=${GIT_COMMIT_AUTHOR_EMAIL}
    image: aiderbot
    pull_policy: never
    command: gunicorn --bind 0.0.0.0:8585 aiderbot.main:app
    environment:
      - REDIS_URL=redis://redis:6379/0
      - FLASK_ENV=production
    volumes:
      - ./persistent-data:/app/persistent-data
    ports:
      - "8585:8585"
    depends_on:
      - redis

  celery_worker:
    image: aiderbot
    pull_policy: never
    command: celery -A aiderbot.celery_tasks worker --loglevel=info
    environment:
      - REDIS_URL=redis://redis:6379/0
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GITHUB_PRIVATE_KEY_PATH=${GITHUB_PRIVATE_KEY_PATH}
    volumes:
      - ./persistent-data:/app/persistent-data
    depends_on:
      - redis
      - web

  redis:
    image: redis:alpine
