version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST: redis
      - REDIS_PORT: 6379
      - REDIS_DB: 0
      - REDIS_PASSWORD: HIXSjIhPiMyYLi1uDXJiaAZ6W2YL2bAY
      - FLASK_ENV: production

  redis:
    image: redis:alpine
    command: redis-server --requirepass HIXSjIhPiMyYLi1uDXJiaAZ6W2YL2bAY
    ports:
      - "6379:6379"
