app = "github-app-aider"
primary_region = "syd"

[build]
  dockerfile = "Dockerfile"

[env]
  FLASK_ENV = "production"

[http_service]
  internal_port = 8585
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[mounts]
  source = "github_private_key"
  destination = "/app/github-private-key.pem"
